## 배열 조회

In [2]:
## 배열 속성 정보

def array_info(array) :
    print(array)
    print('ndim :', array.ndim)
    print('shape :', array.shape)
    print('dtype :', array.dtype)
    print('size :', array.size)
    print('itemsize :', array.itemsize)
    print('nbytes :', array.nbytes)
    print('strides :', array.strides)

In [7]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
            
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [8]:
array_info(a1)

[1 2 3 4 5]
ndim : 1
shape : (5,)
dtype : int32
size : 5
itemsize : 4
nbytes : 20
strides : (4,)


In [10]:
array_info(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
ndim : 2
shape : (3, 3)
dtype : int32
size : 9
itemsize : 4
nbytes : 36
strides : (12, 4)


In [11]:
array_info(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
ndim : 3
shape : (3, 3, 3)
dtype : int32
size : 27
itemsize : 4
nbytes : 108
strides : (36, 12, 4)


### 인덱싱(Indexing)

In [12]:
print(a1)

print(a1[0])
print(a1[1])    # -는 뒤에서부터
print(a1[-1])
print(a1[-2])

[1 2 3 4 5]
1
2
5
4


In [13]:
print(a2)
print(a2[0, 0])
print(a2[1, 1])
print(a2[2, 2])
print(a2[0, 2])
print(a2[2, -1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
5
9
3
9


In [14]:
print(a3)
print(a3[0, 0, 0])
print(a3[1, 1, 1])
print(a3[2, 2, 2])
print(a3[0, -2, -1])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
1
5
9
6


### 슬라이싱(Slicing)

In [15]:
# 배열의 특정 부분(구간)을 선택하는데 사용됩니다.

# 슬라이싱 구문 : [ 시작 : 끝 : 간격 ]
# 시작 : 선택된 요소의 시작 인덱스
# 끝 : 선택된 요소 -1까지의 인덱스
# 간격 : 선택된 요소 사이의 간격

print(a1)
print(a1[0:2])  # 0번째부터 2번째 앞까지
print(a1[0:])   # 0번째부터 끝까지
print(a1[:2])   # 처음부터 2번째 앞까지
print(a1[::2])  # 처음부터 끝까지 2씩 증가
print(a1[::-1]) # 처음부터 끝까지 역순으로





[1 2 3 4 5]
[1 2]
[1 2 3 4 5]
[1 2]
[1 3 5]
[5 4 3 2 1]


In [16]:
print(a2)
print(a2[0:2, 0:2]) # 0번째부터 2번째 앞까지, 0번째부터 2번째 앞까지
print(a2[1:, 1:])   # 1번째부터 끝까지, 1번째부터 끝까지
print(a2[:2, :2])  # 처음부터 2번째 앞까지, 처음부터 2번째 앞까지
print(a2[1:,::-1]) # 1번째부터 끝까지, 끝부터 처음까지 역순으로
print(a2[::-1,::-1]) # 끝부터 처음까지 역순으로, 끝부터 처음까지 역순으로

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[5 6]
 [8 9]]
[[1 2]
 [4 5]]
[[6 5 4]
 [9 8 7]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [18]:
## 불리언 인덱싱(Boolean Indexing)

# 배열의 요소를 선택하는 데 사용되는 또 다른 방법은 불리언 인덱싱입니다.
# 불리언 인덱싱은 배열의 요소를 선택하는 데 조건을 사용합니다.

print(a1)

bi = [False, True, True, False, True]   
print(a1[bi]) # True에 해당하는 요소만 선택

[1 2 3 4 5]
[2 3 5]


In [20]:
print(a2)

bi = np.random.randint(0,2,(3,3), dtype=bool) # 0과 1사이의 랜덤한 값으로 3x3 배열 생성
#0은 false, 1은 true
print(bi)
print(a2[bi]) # True에 해당하는 요소만 선택


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False  True False]
 [False  True False]
 [False False  True]]
[2 5 9]


In [30]:
print(a1)
print([a1[0],a1[2]])
ind = [0,2]
print(a1[ind])  
print("---")
ind = np.array([[0,1],[2,0]])
print(a1[ind])

[1 2 3 4 5]
[1, 3]
[1 3]
---
[[1 2]
 [3 1]]


In [25]:
print(a2)
print(a2[[0, 1], [1, 1]]) # (0, 0), (1, 1), (2, 2)에 해당하는 요소 선택

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 5]
