## 배열 값 삽입/수정/삭제/복사

In [ ]:
## 배열 값 삽입.
   #인덱스를 지정하여 값을 추가할 수 있습니다.
   #insert() 메서드를 사용하여 배열의 특정 위치에 값을 추가할 수 있습니다.
    #insert() 메서드는 두 개의 인수를 사용합니다. 
    # 첫 번째 인수는 삽입할 값의 인덱스이고 두 번째 인수는 삽입할 값입니다.
   #배열의 끝에 값을 추가하려면 append() 메서드를 사용하십시오.
   # 슬라이싱을 사용하여 배열의 특정 위치에 여러 값을 추가할 수도 있습니다.
   # concatentation을 사용하여 두 개의 배열을 결합할 수도 있습니다. 

In [1]:
import numpy as np
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
            
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [8]:

print(a1)
b1 = np.insert(a1, 1, 10) # 1번째 인덱스에 10을 추가
print(b1)
print(a1) # 원본 배열은 변경되지 않습니다.
c1 = np.insert(a1, 3, 10)
print(c1)

print()
print("-------")
print(a2)
print()
print("-------")
b2 = np.insert(a2, 1, 10, axis=0) # 2차원이기 때문에 axis(축)를 지정해야 합니다.
#로우방향 1번째 인덱스에 10을 추가
# axis가 1이면 열(column)에 추가되고 axis가 0이면 행(row)에 추가됩니다.
print(b2)
print()
print("-------")
c2 = np.insert(a2, 1, 10, axis=1) #열방향 1번째 인덱스에 10을 추가 
print(c2)

[1 2 3 4 5]
[ 1 10  2  3  4  5]
[1 2 3 4 5]
[ 1  2  3 10  4  5]

-------
[[1 2 3]
 [4 5 6]
 [7 8 9]]

-------
[[ 1  2  3]
 [10 10 10]
 [ 4  5  6]
 [ 7  8  9]]

-------
[[ 1 10  2  3]
 [ 4 10  5  6]
 [ 7 10  8  9]]
