## 파이썬 라이브러리 : 넘파이 
 ### 행렬 계산 라이브러리
 #### 행렬 & 선형대수의 계산을 편하게 하기 위해 만들어진 라이브러리 

### NumPy 특징
### Numerical Python의 약자
------

#### 고성능 과학 계산용 패키지로 강력한 N차원 배열 객체
#### 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
#### 정교한 브로드캐스팅(broadcasting) 기능
#### 파이썬의 자료형 list와 비슷하지만, 더 빠르고 메모리를 효율적으로 관리
#### 반복문 없이 데이터 배열에 대한 처리를 지원하여 빠르고 편리
#### 데이터 과학 도구에 대한 생태계의 핵심을 이루고 있음

In [2]:
import numpy as np
np.__version__

'1.26.4'

In [10]:
a1 = np.array([1, 2, 3, 4, 5]) #1차원 배열
print(a1)
print(type(a1))
print(a1.shape) # shape는 행렬의 모양을 알려줌.  5*1짜리 1차원 행렬
print(a1[0], a1[1], a1[2], a1[3], a1[4])
a1[0] = 4
a1[1] = 5
a1[2] = 6
print(a1)




[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1 2 3 4 5
[4 5 6 4 5]


In [14]:
a2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) #2차원 배열 생성.
print(a2)
print(a2.shape)  #3*3 짜리 2차원 행렬
print(a2[0, 0], a2[1, 1], a2[2, 2]) #인덱스로 값에 접근


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
1 5 9


In [16]:
a3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]], 
            
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]) #3차원 배열 생성  3*3*3 짜리 3차원 행렬
print(a3)

print(a3.shape) #3*3*3 짜리 3차원 행렬

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
(3, 3, 3)


In [ ]:
# zeros() : 모든 요소를 0으로 채운 배열을 생성
# ones() : 모든 요소를 1로 채운 배열을 생성
# full() : 모든 요소를 지정한 값으로 채운 배열을 생성
# eye() : 단위 행렬 생성 : 주대각선의 원소가 모두 1이고 나머지는 0인 정사각 행렬
   # 행렬곱셉에서 항등원으로 사용할 때
   # 특정 변환이나 연산에서 기준점으로 사용할 때
   # 행렬연산/머신러닝/이미지 처리/ 통계 분석 등에 사용됩니다.
# tri() : 하삼각행렬 생성
   # 주대각선과 그 아래 부분이 1로 채워지고, 나머지는 0으로 채워집니다.
   # 추후에, 신호처리/수치해석/그래픽스 등에 사용됩니다.
# empty() : 초기화되지 않은 배열 생성
   # 초기화가 없어서 배열 생성비용 저렴하고 빠름
   # 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음
#_like() : 주어진 배열과 동일한 shape와 dtype을 가지는 행렬 생성
   # np.zeros_like(), np.ones_like(), np.full_like(), np.empty_like()
      

In [17]:
#zeros() : 모든 요소를 0으로 채운 배열을 생성
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
# ones() : 모든 요소를 1로 채운 배열을 생성

np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# full() : 모든 요소를 지정한 값으로 채운 배열을 생성

np.full((3, 3), 7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [20]:
# eye() : 단위 행렬 생성 : 주대각선의 원소가 모두 1이고 나머지는 0인 정사각 행렬

np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [21]:
# tri() : 하삼각행렬 생성
   # 주대각선과 그 아래 부분이 1로 채워지고, 나머지는 0으로 채워집니다.
   # 추후에, 신호처리/수치해석/그래픽스 등에 사용됩니다.
   
np.tri(6)

array([[1., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
# empty() : 초기화되지 않은 배열 생성
   # 초기화가 없어서 배열 생성비용 저렴하고 빠름
   # 초기화되지 않아서 기존 메모리 위치에 존재하는 값이 있음
     # 따라서, 뭐가 나올지 모름
     
     
np.empty(10)     

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
#_like() : 주어진 배열과 동일한 shape와 dtype을 가지는 행렬 생성
   # np.zeros_like(), np.ones_like(), np.full_like(), np.empty_like()
   
print(a1)
np.zeros_like(a1)   

[4 5 6 4 5]


array([0, 0, 0, 0, 0])

In [29]:
#_like() : 주어진 배열과 동일한 shape와 dtype을 가지는 행렬 생성
   # np.zeros_like(), np.ones_like(), np.full_like(), np.empty_like()
print(a2)
np.ones_like(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
#_like() : 주어진 배열과 동일한 shape와 dtype을 가지는 행렬 생성
   # np.zeros_like(), np.ones_like(), np.full_like(), np.empty_like()
   
print(a3) 
t=type(a3)
print(t)
np.full_like(a3, 666)    

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
<class 'numpy.ndarray'>


array([[[666, 666, 666],
        [666, 666, 666],
        [666, 666, 666]],

       [[666, 666, 666],
        [666, 666, 666],
        [666, 666, 666]],

       [[666, 666, 666],
        [666, 666, 666],
        [666, 666, 666]]])

In [34]:
print(a3)
np.empty_like(a3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [ ]:

#  - arange() : 정수 범위로 배열 생성

# - linspace() : 범위 내에서 균등 간격의 배열 생성

# - logspace() : 범위 내에서 균등간격으로 로그 스케일로 배열 생성

In [36]:
#  - arange() : 정수 범위로 배열 생성

np.arange(0,24,2)
# arange(시작, 끝, 단계)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [37]:
# - linspace() : 범위 내에서 균등 간격의 배열 생성
# 간격은 알아서 계산함.
#linspace(시작점,끝점,개수)

np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [38]:
# - logspace() : 범위 내에서 균등간격으로 로그 스케일로 배열 생성

np.logspace(0.1, 1, 20)

array([ 1.25892541,  1.40400425,  1.565802  ,  1.74624535,  1.94748304,
        2.1719114 ,  2.42220294,  2.70133812,  3.0126409 ,  3.35981829,
        3.74700446,  4.17881006,  4.66037703,  5.19743987,  5.79639395,
        6.46437163,  7.2093272 ,  8.04013161,  8.9666781 , 10.        ])

In [4]:
# random.random() : 랜덤한 수의 실수 배열 생성
np.random.random((3, 3))    

array([[0.66469268, 0.40323265, 0.67147299],
       [0.76145915, 0.62707404, 0.6664596 ],
       [0.53548092, 0.44736816, 0.33989466]])

In [8]:
# random.randint() : 일정 구간의 랜덤한 수의 정수 배열 생성

np.random.randint(0,10,(3,3))

array([[1, 7, 8],
       [5, 3, 0],
       [4, 1, 4]])

In [10]:
# random.normal() : 정규분포(normal distribution)를 고려한 랜덤한 수의 배열 생성

#평균 0 표준편차 1인 정규분포를 따르는 3*3 행렬
np.random.normal(0, 1, (3, 3))

array([[-0.29093964, -0.66629951, -0.36483789],
       [-0.01892186,  1.38834522,  1.03613958],
       [ 1.28452997, -0.64699791, -0.74889667]])

In [13]:
# random.rand() : 균등분포(uniform distribution)를 고려한 랜덤한 수의 배열 생성[양수만]

np.random.rand(3, 3)

array([[0.45289459, 0.15643965, 0.72561567],
       [0.67841255, 0.89281351, 0.09552442],
       [0.38448967, 0.49475087, 0.43219661]])

In [14]:
# random.randn() : 표준 정규 분포(standard normal distribution)를 고려한 랜덤한 수의 배열 생성
np.random.randn(3, 3)

array([[-0.35549558,  2.24905484, -0.54189294],
       [ 0.94960807,  0.4450994 , -0.19553959],
       [-1.22595573, -1.62246068,  0.69321088]])

In [16]:
np.zeros(20, dtype=int)

# dtype은 넘파이의 데이터 타입을 지정해주는 파라미터

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.ones((3, 3), dtype=bool) 

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
np.full((3,3),1.0,dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
date = np.array('2024-07-07', dtype=np.datetime64)
print(date)

2024-07-07


In [22]:
# 특정 날짜부터 특정 일수까지의 날짜를 배열로 생성

date + np.arange(12)

array(['2024-07-07', '2024-07-08', '2024-07-09', '2024-07-10',
       '2024-07-11', '2024-07-12', '2024-07-13', '2024-07-14',
       '2024-07-15', '2024-07-16', '2024-07-17', '2024-07-18'],
      dtype='datetime64[D]')

In [23]:
datetime = np.datetime64('2024-07-07 12:00')
print(datetime)

2024-07-07T12:00
