## 모듈과 패키지

In [ ]:
#모듈은 변수, 함수, 클래스를 담고 있는 파일 (.py)
#패키지는 여러 모듈을 묶은 것(폴더)

#import 모듈이름

#모듈이름.변수
#모듈이름.함수()



In [3]:
import math    #math 모듈을 가져옴
print(math.pi) #math 모듈의 변수 pi 출력 파이값 출력  
# pritn(pi) #<- 이렇게 하면 오류남
print(math.sqrt(4)) #math 모듈의 함수 sqrt(제곱근)에 4를 넣어서 출력
#파이썬의 방식은 이거.!

3.141592653589793
2.0


In [ ]:
from math import pi , sqrt #math 모듈에서 pi, sqrt만 가져옴
print(pi)
print(sqrt(4)) # 여기서는 오히려 math.을 쓰면 오류남

In [ ]:
#하나씩 불러오는게 귀찮으면
from math import * #math 모듈의 모든 것을 가져옴   *이 all이란 뜻


In [ ]:
# import 패키지
# import 패키지.모듈
# import 패키지.모듈1, 패키지.모듈2, 패키지.모듈3
# import 패키지.모듈.클래스
# import 패키지.모듈.함수
# import 패키지.모듈.변수


In [4]:
import numpy as np # numpy는 라이브러리 ( 패키지와 모듈들을 모아놓은 것) (numerical python)

a=np.array([1,2,3]) #numpy 모듈의 array 함수를 사용
print(a)
type(np.array)
  

[1 2 3]


builtin_function_or_method

In [9]:
import numpy.random 
print(numpy.random.randn(3,3)) #numpy 모듈의 random 모듈의 randn 함수를 사용 (3,3)은 3행 3열의 행렬을 만들어라는 뜻 randn은 정규분포를 따르는 난수를 생성하는 함수


[[ 0.55254004  0.81679376 -0.75011049]
 [ 0.94168399  0.23827866  0.28095828]
 [ 0.55040215  0.2025992   0.36338956]]


In [11]:
import numpy.random as nr
print(nr.randn(3,3))

[[ 1.0032798  -0.0662263   2.11943349]
 [ 0.56464584 -0.44550887 -0.01942321]
 [-0.9830618  -0.55509598 -1.73716908]]


In [12]:
import numpy.random as nr
print(nr.rand(3,3))  # rand는 0~1사이의 난수를 생성하는 함수

[[0.529527   0.56974083 0.80114858]
 [0.46150983 0.09704753 0.69514945]
 [0.82485716 0.68003941 0.48954148]]


In [13]:
from numpy.random import randn as rn, rand as r
print(rn(3,3))
print(r(3,3))

[[-0.9809718  -0.02887651 -0.13270607]
 [ 0.004241   -0.26926176  2.44446434]
 [-1.11243991 -0.541837    0.4562098 ]]
[[0.34950711 0.54151766 0.68493339]
 [0.84806941 0.97632792 0.97412613]
 [0.31086044 0.19141202 0.43298082]]
