## Numpy 본격적으로

In [3]:
import numpy as np

a=np.array([1,2,3,4]) #list가 입력으로 들어가는 함수.
print(a)
print(type(a))  #<class 'numpy.ndarray'> ndarray는 넘파이의 기본 자료형이다.
print(a.dtype)  #int64 dtype은 데이터 타입을 의미한다.
print(a.size)   #4 size는 배열의 크기를 의미한다.
print(a.shape)  #(4,) shape는   배열의 형태 즉, 행렬의 모양을 알려준다.


b=np.array([1,2,3.1,4]) #정수와 실수가 혼합되어 있으면 실수로 변환된다.

print(b.dtype)  #float64



[1 2 3 4]
<class 'numpy.ndarray'>
int32
4
(4,)
float64


In [12]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]]) #2차원 배열
print(A)
# B = np.array([[1,2,3],[4,,6],[7,8,9]])  #이러면 오류가 발생 이유는 : 리스트와는 달리 이제는 행렬이기 때문에 각 행에 해당하는 숫자의 개수가 같아야 함

print(A.shape)
print(A.ndim) #몇차원의 배열인지 알려준다
print(A.size) #배열의 크기를 알려준다.

print()
print("----------------------")
#3차원 배열은 어떻게 만들까?
C = np.array([[[1,2],[3,4]],[[5,6],[7,8]]]) #3차원 배열
print(C)
print(C.shape)
print(C.ndim)
print(C.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
9

----------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3
8


In [26]:
print(np.zeros(5)) #0으로 채워진 배열을 만들어준다.
print(np.zeros_like(C)) #C와 같은 모양의 0으로 채워진 배열을 만들어준다.

print(np.ones(5)) #1로 채워진 배열을 만들어준다.
print(np.ones_like(A))
print(np.zeros((3,4)))  #튜플로 입력을 해줘야 함 그냥 np.zeros(3,4)은 안됨.  -> 다른 라이브러리 torch에서는 가능하다.

import torch
print(torch.zeros(3,4)) #torch에서는 가능하다.


print(np.arange(3,10,2)) #range랑 같은데 array로 만들어준다.
print(np.arange(0,1,0.1)) #arange는 소수점 간격이 가능하다. 첫번째 인자부터 두번째 인자 미만까지


print(np.linspace(0,1,10)) #0에서부터 1까지 구간을 10개로균일하게 나눠준다/ 나누는 간격은 알아서 계산해준다.


[0. 0. 0. 0. 0.]
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]
[1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
