## 넘파이 인덱싱 & 슬라이싱

In [ ]:
# 인덱싱:
# 단일 요소 접근: array[i] 형태로 i번째 요소에 접근합니다.
# 다차원 배열: array[i,j] 형태로 i행 j열의 요소에 접근합니다.
# 음수 인덱스: array[-1]은 마지막 요소를 의미합니다.



# 슬라이싱:
# 기본 형태: array[start:stop:step]
# start: 시작 인덱스 (기본값 0)
# stop: 끝 인덱스 (포함되지 않음)
# step: 간격 (기본값 1)

In [1]:
# 인덱싱
# 단일 요소 접근: array[i] 형태로 i번째 요소에 접근합니다.
# 다차원 배열: array[i,j] 형태로 i행 j열의 요소에 접근합니다.
# 음수 인덱스: array[-1]은 마지막 요소를 의미합니다.

import numpy as np

a = np.array([1, 2, 3, 4, 5,6,7,8,9,10])
print(a[0])
print(a[1])
print(a[-1])



1
2
10


In [2]:
# 슬라이싱:
# 기본 형태: array[start:stop:step]
# start: 시작 인덱스 (기본값 0)
# stop: 끝 인덱스 (포함되지 않음)
# step: 간격 (기본값 1)


a = np.array([1, 2, 3, 4, 5,6,7,8,9,10])

print(a[1:4])
print(a[7:])

[2 3 4]
[ 8  9 10]


In [13]:
# 행렬에 대한 인덱싱과 슬라이싱

# 인덱싱:
# 단일 요소 접근: array[i] 형태로 i번째 요소에 접근합니다.
# 다차원 배열: array[i,j] 형태로 i행 j열의 요소에 접근합니다.
# 음수 인덱스: array[-1]은 마지막 요소를 의미합니다.

# 슬라이싱:
# 기본 형태: array[start:stop:step]
# start: 시작 인덱스 (기본값 0)
# stop: 끝 인덱스 (포함되지 않음)
# step: 간격 (기본값 1)



#행렬이 만들어져 있을 때의 인덱싱과 슬라이싱 적용 [행부터 접근]

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#인덱싱
print(A[0]) #0번째 행을 가져온다
print(A[-1]) #마지막 행을 가져온다

print("---")
#슬라이싱
print(A[0:2]) #0번째 행부터 2번째 행 전까지 가져온다
print(A[:]) #모든 행을 가져온다

# 특정행, 특정열에 접근하기
print(A[0][2])
print(A[0,2]) #둘다 0번째 행의 2번째 열을 가져온다 넘파이에서 제공하는 기능, 이렇게 사용하는게 더 효율적이다

print(A[1])
print(A[1, :]) #1번째 행의 모든 열을 가져온다 넘파이에서 제공하는 기능, 이렇게 사용하는게 더 효율적이다

print(A[1,0:3:2]) #1번째 행의 0번째 열부터 3번째 열까지 2간격으로 가져온다
print(A[:,2]) #모든 행의 2번째 열을 가져온다

[1 2 3]
[7 8 9]
---
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[4 5 6]
[4 5 6]
[4 6]
[3 6 9]


In [22]:
# boolean 인덱싱 
# 넘파이의 boolean 인덱싱은 배열 각 요소에 대한 비교 여부를 True, False로 출력하는 방식입니다.

a = [1,2,3,4,5,3,3] #리스트와 인티져 값을 비교할 수 없기에 false가 나온다
print(a==3)

A=np.array([[1,2,3,4],[5,3,7,3]]) #각 요소에 대해 비교를 한다
print(A==3)
print()
print("----")

t = A[A==3] #3인 요소만 가져온다 boolean 인덱싱에서 true인 값만 가져온다, true인 성분만을 인덱싱 한 것.
print(t)
print()
print("----")
A[A==3] = 120

print(A)

print()
print("----")

A = np.array([[1,2],[3,4],[5,6],[7,8]])
B = np.array([True, False, True, False])

A[B, :] #A에서 True인 행만 가져온다

False
[[False False  True False]
 [False  True False  True]]

----
[3 3 3]

----
[[  1   2 120   4]
 [  5 120   7 120]]

----


array([[1, 2],
       [5, 6]])

In [25]:
# 3차원 행렬의 인덱싱

A = np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],[[12,13,14,15],[16,17,18,19],[20,21,22,23]]])

print(A)
print(A.shape)

print(A[0,1,2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6
