## numpy의 여러 함수들

In [9]:
import numpy as np
A = np.random.randn(3,3) # 3*3사이즈의 정규분포 양수음수 모두
B = np.random.rand(3,3) # 3*3사이즈의 0~1사이의 값


print(A)
print(B)

print()
print("----")

print(A[:,0])  #A의 전체 행의 0번째 열
print(A[:,0]<0) #A의 전체 행의 0번째 열이 0보다 작은지 확인

[[-2.17181032  0.03509551  0.57155311]
 [-0.57599589 -0.92630955 -0.77794833]
 [-0.58018615 -1.68890662  0.1392245 ]]
[[0.41475815 0.54966648 0.48746868]
 [0.99755826 0.49860676 0.03324121]
 [0.23035216 0.3674196  0.05057625]]

----
[-2.17181032 -0.57599589 -0.58018615]
[ True  True  True]


In [14]:
A = np.random.randn(3,4)

print(A)
print()
print(np.max(A))
print(np.max(A, axis=0)) #열의 최대값
print(np.max(A, axis=1)) #행의 최대값
print(np.max(A, axis=0, keepdims=True)) #열의 최대값을 2차원으로 유지
print(np.max(A, axis=1, keepdims=True)) #행의 최대값을 2차원으로 유지 
print()
print(np.min(A))
print(np.min(A, axis=0)) #열의 최소값
print(np.min(A, axis=1)) #행의 최소값
print()
print(np.argmax(A))
print(np.argmax(A, axis=0)) # 각각 열에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A, axis=1)) # 각각 행에서 가장 큰 애가 존재하는 인덱스

[[-1.58173068 -0.5081404   0.44947693 -2.46429572]
 [-1.1774745   0.03240194  0.31259734  0.04854311]
 [-1.81513936  1.25831147  0.17677805  0.34881175]]

1.258311469577693
[-1.1774745   1.25831147  0.44947693  0.34881175]
[0.44947693 0.31259734 1.25831147]
[[-1.1774745   1.25831147  0.44947693  0.34881175]]
[[0.44947693]
 [0.31259734]
 [1.25831147]]

-2.464295722186465
[-1.81513936 -0.5081404   0.17677805 -2.46429572]
[-2.46429572 -1.1774745  -1.81513936]

9
[1 2 0 2]


In [22]:
a = np.random.randn(6,1)
print(a)

print()
s = a_sorted = np.sort(a, axis=0) #오름차순으로 뽑기
print(s)
print()
cs = a_csorted = np.flipud(a_sorted) #내림차순으로 뽑기
print(cs)

[[-1.05108453]
 [-0.93575662]
 [-1.06781933]
 [ 0.86651435]
 [-0.3468768 ]
 [ 0.14431134]]

[[-1.06781933]
 [-1.05108453]
 [-0.93575662]
 [-0.3468768 ]
 [ 0.14431134]
 [ 0.86651435]]

[[ 0.86651435]
 [ 0.14431134]
 [-0.3468768 ]
 [-0.93575662]
 [-1.05108453]
 [-1.06781933]]


In [25]:
A = np.random.randn(4,7)
print(A)  # 4행 7열의 랜덤 정규분포 행렬 A 출력

print()
print("---")

print(np.sum(A))  # A 행렬의 모든 원소의 합 출력
print(np.sum(A, axis=1))  # A 행렬의 각 행의 합을 계산 (결과: 1차원 배열)
print(np.sum(A, axis=1, keepdims=True))  # A 행렬의 각 행의 합을 계산 (결과: 4행 1열의 2차원 배열)


# axis=1은 행을 따라 계산을 수행하라는 의미이며,
# keepdims=True는 결과를 원래 차원과 동일하게 유지하라는 의미

print()
print("---")

print(np.mean(A))  # A 행렬의 모든 원소의 평균 출력
print(np.mean(A, axis=1))  # A 행렬의 각 행의 평균을 계산 (결과: 1차원 배열)
print(np.mean(A, axis=1, keepdims=True))  # A 행렬의 각 행의 평균을 계산 (결과: 4행 1열의 2차원 배열)

print()
print("---")

print(np.std(A))  # A 행렬의 모든 원소의 표준편차 출력



[[ 1.91232452 -0.81694693  0.36029213  1.02422025  0.61259652 -0.39144398
   2.17932608]
 [ 1.6912682  -1.34317186 -0.18432008  3.46164601  0.52744794 -2.12432622
   1.44178058]
 [ 1.23411563 -0.22905121 -0.47843588  0.10885581 -1.85583759 -0.86773643
  -1.50270028]
 [ 1.13244354 -0.01308433  0.43641267  0.56040558 -1.23312041  0.97521666
  -2.23873514]]

---
4.379441770180783
[ 4.8803686   3.47032456 -3.59078996 -0.38046143]
[[ 4.8803686 ]
 [ 3.47032456]
 [-3.59078996]
 [-0.38046143]]

---
0.15640863464931368
[ 0.69719551  0.49576065 -0.51296999 -0.05435163]
[[ 0.69719551]
 [ 0.49576065]
 [-0.51296999]
 [-0.05435163]]

---
1.3521082785346406


In [27]:
A = np.random.randint(1, 5, size=(12,))
print(A)  # 1부터 4까지의 정수 중 랜덤하게 12개를 선택하여 1차원 배열 A 생성 및 출력
print(A.shape)  # A의 형태 출력 (12,)

print()
print("---")

B = A.reshape(2, 2, 3)  # A를 2x2x3 형태의 3차원 배열로 재구성
print(B)  # 재구성된 3차원 배열 B 출력

[4 3 1 3 4 1 2 3 1 3 3 1]
(12,)

---
[[[4 3 1]
  [3 4 1]]

 [[2 3 1]
  [3 3 1]]]
