## numpy의 여러 함수들

In [3]:
import numpy as np
A = np.random.randn(3,3) # 3*3사이즈의 정규분포 양수음수 모두 , 튜플값으로 안 넣어도 됨.
B = np.random.rand(3,3) # 3*3사이즈의 0~1사이의 값


print(A)
print(B)

print()
print("----")

print(A[:,0])  #A의 전체 행의 0번째 열
print(A[:,0]<0) #A의 전체 행의 0번째 열이 0보다 작은지 확인
print(A[A[:,0]<0,:])   #A의 전체 행의 0번째 열이 0보다 작은 행렬 출력

[[ 0.08655309 -0.53495988 -0.18080042]
 [-0.26242785  0.78825452 -0.92477496]
 [ 0.44359693  0.23025394 -0.5518144 ]]
[[0.92119262 0.87267843 0.04075366]
 [0.02801301 0.00308063 0.85168635]
 [0.71409445 0.14971538 0.60992577]]

----
[ 0.08655309 -0.26242785  0.44359693]
[False  True False]
[[-0.26242785  0.78825452 -0.92477496]]


In [14]:
A = np.random.randn(3,4)

print(A)
print()
print(np.max(A))
print(np.max(A, axis=0)) #열의 최대값
print(np.max(A, axis=1)) #행의 최대값
print(np.max(A, axis=0, keepdims=True)) #열의 최대값을 2차원으로 유지
print(np.max(A, axis=1, keepdims=True)) #행의 최대값을 2차원으로 유지 
print()
print(np.min(A))
print(np.min(A, axis=0)) #열의 최소값
print(np.min(A, axis=1)) #행의 최소값
print()
print(np.argmax(A))
print(np.argmax(A, axis=0)) # 각각 열에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A, axis=1)) # 각각 행에서 가장 큰 애가 존재하는 인덱스

[[-1.58173068 -0.5081404   0.44947693 -2.46429572]
 [-1.1774745   0.03240194  0.31259734  0.04854311]
 [-1.81513936  1.25831147  0.17677805  0.34881175]]

1.258311469577693
[-1.1774745   1.25831147  0.44947693  0.34881175]
[0.44947693 0.31259734 1.25831147]
[[-1.1774745   1.25831147  0.44947693  0.34881175]]
[[0.44947693]
 [0.31259734]
 [1.25831147]]

-2.464295722186465
[-1.81513936 -0.5081404   0.17677805 -2.46429572]
[-2.46429572 -1.1774745  -1.81513936]

9
[1 2 0 2]


In [12]:
A = np.random.randn(3,4)

print(A)
print("-----")
print(np.abs(A)) #절대값
print("-----")
print(np.sqrt(np.abs(A))) #제곱근
print("-----")
print(np.exp(A)) #지수함수
print("-----")
print(np.log(np.abs(A))) #로그함수
print("-----")
print(np.log(np.exp(1))) # np.exp(1) = e^1
print("-----")
print(np.log10(10)) # 상용로그
print("-----")
print(np.log2(2)) # 밑이 2인 로그
print("-----")
print(np.round(A)) #반올림
print("-----")
print(np.round(A, 2)) #소수점 둘째자리까지 반올림 
print("-----")
print(np.floor(A)) #내림    
print("-----")
print(np.ceil(A)) #올림 

[[ 0.38358386 -0.43470732  1.23382533 -1.05979493]
 [-0.31650701 -0.55433036 -1.45718155 -1.19471285]
 [-0.20523444 -0.76380476 -0.14580609  0.34196123]]
-----
[[0.38358386 0.43470732 1.23382533 1.05979493]
 [0.31650701 0.55433036 1.45718155 1.19471285]
 [0.20523444 0.76380476 0.14580609 0.34196123]]
-----
[[0.61934147 0.65932338 1.1107769  1.02946342]
 [0.56258955 0.74453365 1.20713775 1.09302921]
 [0.45302808 0.87395924 0.38184563 0.58477451]]
-----
[[1.46753461 0.64745414 3.43434192 0.34652686]
 [0.72868991 0.57445681 0.23289174 0.30279089]
 [0.81445635 0.46589045 0.86432529 1.40770571]]
-----
[[-0.95819702 -0.83308231  0.21011936  0.05807543]
 [-1.1504099  -0.58999445  0.37650412  0.17790586]
 [-1.58360235 -0.26944307 -1.92547772 -1.07305792]]
-----
1.0
-----
1.0
-----
1.0
-----
[[ 0. -0.  1. -1.]
 [-0. -1. -1. -1.]
 [-0. -1. -0.  0.]]
-----
[[ 0.38 -0.43  1.23 -1.06]
 [-0.32 -0.55 -1.46 -1.19]
 [-0.21 -0.76 -0.15  0.34]]
-----
[[ 0. -1.  1. -2.]
 [-1. -1. -2. -2.]
 [-1. -1. -1.  0

In [15]:
# sin(pi/6)의 값을 출력합니다. 이는 30도의 사인 값으로, 1/2 (0.5)입니다.
print(np.sin(np.pi/6))
# np.pi/6는 π/6 라디안, 즉 30도를 의미합니다.
# np.sin() 함수는 사인 값을 계산합니다.
# sin(30°) 또는 sin(π/6)의 정확한 값은 1/2 또는 0.5입니다.
# 이 값은 직각삼각형에서 빗변이 1일 때 30도 각에 대한 대변의 길이를 나타냅니다.

# cos(pi/3)의 값을 출력합니다. 이는 60도의 코사인 값으로, 1/2 (0.5)입니다.
print(np.cos(np.pi/3))
# np.pi/3는 π/3 라디안, 즉 60도를 의미합니다.
# np.cos() 함수는 코사인 값을 계산합니다.
# cos(60°) 또는 cos(π/3)의 정확한 값은 1/2 또는 0.5입니다.
# 이 값은 직각삼각형에서 빗변이 1일 때 60도 각에 대한 인접변의 길이를 나타냅니다.

# tan(pi/3)의 값을 출력합니다. 이는 60도의 탄젠트 값으로, √3 (약 1.732)입니다.
print(np.tan(np.pi/3))
# np.tan() 함수는 탄젠트 값을 계산합니다.
# tan(60°) 또는 tan(π/3)의 정확한 값은 √3입니다.
# √3의 근사값은 약 1.732050807568877입니다.
# 탄젠트는 사인을 코사인으로 나눈 값과 같습니다. 여기서는 √3/3 ÷ 1/2 = √3입니다.

0.49999999999999994
0.5000000000000001
1.7320508075688767


In [16]:
np.nan # not a number

print(np.isnan([1,2,np.nan,3,4,])) #nan이 있는지 확인
print(np.isinf([1,2,np.inf,3,4,])) #무한대가 있는지 확인

[False False  True False False]
[False False  True False False]


In [22]:
a = np.random.randn(6,1)
print(a)

print()
s = a_sorted = np.sort(a, axis=0) #오름차순으로 뽑기
print(s)
print()
cs = a_csorted = np.flipud(a_sorted) #내림차순으로 뽑기
print(cs)

[[-1.05108453]
 [-0.93575662]
 [-1.06781933]
 [ 0.86651435]
 [-0.3468768 ]
 [ 0.14431134]]

[[-1.06781933]
 [-1.05108453]
 [-0.93575662]
 [-0.3468768 ]
 [ 0.14431134]
 [ 0.86651435]]

[[ 0.86651435]
 [ 0.14431134]
 [-0.3468768 ]
 [-0.93575662]
 [-1.05108453]
 [-1.06781933]]


In [25]:
A = np.random.randn(4,7)
print(A)  # 4행 7열의 랜덤 정규분포 행렬 A 출력

print()
print("---")

print(np.sum(A))  # A 행렬의 모든 원소의 합 출력
print(np.sum(A, axis=1))  # A 행렬의 각 행의 합을 계산 (결과: 1차원 배열)
print(np.sum(A, axis=1, keepdims=True))  # A 행렬의 각 행의 합을 계산 (결과: 4행 1열의 2차원 배열)


# axis=1은 행을 따라 계산을 수행하라는 의미이며,
# keepdims=True는 결과를 원래 차원과 동일하게 유지하라는 의미

print()
print("---")

print(np.mean(A))  # A 행렬의 모든 원소의 평균 출력
print(np.mean(A, axis=1))  # A 행렬의 각 행의 평균을 계산 (결과: 1차원 배열)
print(np.mean(A, axis=1, keepdims=True))  # A 행렬의 각 행의 평균을 계산 (결과: 4행 1열의 2차원 배열)

print()
print("---")

print(np.std(A))  # A 행렬의 모든 원소의 표준편차 출력


# 표준편차란:

# 정의: 데이터가 평균으로부터 얼마나 퍼져있는지를 나타내는 지표입니다.
# 계산: 각 데이터 포인트와 평균의 차이를 제곱하고, 그 제곱값들의 평균을 구한 뒤, 제곱근을 취합니다.
# 의미: 데이터의 분산 정도를 나타내며, 값이 클수록 데이터가 넓게 퍼져있다는 것을 의미합니다.

# 데이터 분석에서의 사용:

# 데이터 분포 이해:

# 데이터의 퍼짐 정도를 파악하여 전체적인 분포를 이해할 수 있습니다.


# 이상치 탐지:

# 평균에서 몇 표준편차 떨어진 데이터를 이상치로 간주할 수 있습니다.


# 신뢰구간 설정:

# 정규분포를 따르는 데이터의 경우, 표준편차를 이용해 신뢰구간을 설정할 수 있습니다.


# 데이터 정규화:

# 서로 다른 척도의 데이터를 비교할 때 표준화(z-score)에 사용됩니다.


# 품질 관리:

# 제조 과정에서 제품의 균일성을 평가할 때 사용됩니다.


# 금융 분석:

# 투자의 위험도를 측정하는 데 사용됩니다.


# 과학적 실험:

# 실험 결과의 정밀도를 평가하는 데 사용됩니다


[[ 1.91232452 -0.81694693  0.36029213  1.02422025  0.61259652 -0.39144398
   2.17932608]
 [ 1.6912682  -1.34317186 -0.18432008  3.46164601  0.52744794 -2.12432622
   1.44178058]
 [ 1.23411563 -0.22905121 -0.47843588  0.10885581 -1.85583759 -0.86773643
  -1.50270028]
 [ 1.13244354 -0.01308433  0.43641267  0.56040558 -1.23312041  0.97521666
  -2.23873514]]

---
4.379441770180783
[ 4.8803686   3.47032456 -3.59078996 -0.38046143]
[[ 4.8803686 ]
 [ 3.47032456]
 [-3.59078996]
 [-0.38046143]]

---
0.15640863464931368
[ 0.69719551  0.49576065 -0.51296999 -0.05435163]
[[ 0.69719551]
 [ 0.49576065]
 [-0.51296999]
 [-0.05435163]]

---
1.3521082785346406


In [17]:
A = np.random.randint(1, 5, size=(12,))
print(A)  # 1부터 4까지의 정수 중 랜덤하게 12개를 선택하여 1차원 배열 A 생성 및 출력
print(A.shape)  # A의 형태 출력 (12,)

print()
print("---")

B = A.reshape(3, 2, 2)  # A를 2x2x3 형태의 3차원 배열로 재구성
print(B)  # 재구성된 3차원 배열 B 출력

[2 3 4 3 4 3 1 2 2 3 3 1]
(12,)

---
[[[2 3]
  [4 3]]

 [[4 3]
  [1 2]]

 [[2 3]
  [3 1]]]


In [22]:
a= np.array([1,2,3,4,5])
b= np.array([3,5,7,9,11])

print(np.sum(a*b)) # 각 요소별 곱셉을 하고 모두 더합니다.

a=a.reshape(5,1)    
b=b.reshape(5,1)
print(a.T@b) #a의 전치행렬과 b를 곱합니다.  T = transpose()와 같은 의미입니다.


A  = np.random.randn(4,3,2)
print(A.transpose(0,1,2).shape) # 3차원 배열의 축을 바꿀 수 있습니다.
print(A.transpose(2,0,1).shape)


125
[[125]]
(4, 3, 2)
(2, 4, 3)


In [28]:
A=np.arange(20)
print(A)
print(A.reshape(4,5))   
print(A.reshape(4,-1).shape)  #(-1의 의미) : 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) #2차원 행 벡터
print(A.reshape(-1,1).shape) #2차원 열 벡터 


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)
(2, 2, 5)
(1, 20)
(20, 1)


In [36]:
x=np.random.randn(2,3,4,5,6) #5차원 배열
print(x[1,2,:,:,:].shape) #3,4,5,차원만 가져옴/ 첫번째 층에서의 두번째 항목과 두번째층의 세번째 항목은 존재x

print(x[1,2,...].shape) #위와 같은 의미
print(x[:,:,:,:,3].shape)
print(x[...,3].shape)
print("----")

print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape)

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(2, 3, 4, 5)
----
(3, 4, 6)
(3, 4, 6)


In [47]:
A=np.ones((2,2))
B=np.zeros((2,2))

C= np.hstack([A,B])  #가로로 합침
print(C)

D = np.vstack([A,B]) #세로로 합침
print(D)

print("-----")

E = np.block([A,B]) #가로로 합침
print(E)

F = np.block([[A],[B]]) #세로로 합침
print(F)

print("-----")
G=np.block([[[A]], [[B]]  ]) #3차원으로 합침 2*2*2
print(G)

[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
-----
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
-----
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]


In [49]:
A = np.random.randn(1,1,1,3,1,1,4,1)

print(A.shape)
print(A.squeeze().shape)   
# squeeze() 함수는 배열에서 크기가 1인 차원을 모두 제거합니다.
# squeeze() 함수를 사용하여 크기가 1인 불필요한 차원을 모두 제거합니다.

#원하는 자리의 1을 제거.
print(A.squeeze(axis=(0,1,2)).shape)  # 1번째 차원 제거

(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(3, 1, 1, 4, 1)


In [51]:
A= np.random.randn(3,4)  
# np.random.randn()은 표준 정규 분포에서 무작위로 숫자를 생성합니다.
# 여기서는 3행 4열의 2차원 배열을 생성합니다.

A1 = A[np.newaxis, :, :]
# np.newaxis는 새로운 축(차원)을 추가하는 특별한 인덱스입니다.
# :, :는 기존의 모든 행과 열을 그대로 유지한다는 의미입니다.
# 이 연산은 A의 가장 앞에 새로운 차원을 추가합니다.
# 새로 추가되는 차원의 크기는 1입니다.



print(A1.shape)

(1, 3, 4)
